# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'FNKRunnerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Masonry'
  pod 'ORPatchFile', :path => '../'
  pod 'FNKRunner', :path => '../'
  

end
